name: activate-prism
on: [push]
jobs:
  prism-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: prism install
        run: npm i -g @stoplight/prism-cli
      - name: activation prism
        run: prism mock ./docs/swagger.yaml -p 14278 &
      - name: curl test
        run: curl http://127.0.0.1:14278/test
