name: test
on: [push]
jobs:
  github-actions-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: test run
        run: |
          npm i -g @stoplight/prism-cli
          prism mock docs.swagger.yaml -p 14278&
          curl http://127.0.0.1:14278/test
